# Generated by Django 3.1.2 on 2020-10-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date_pub',
            new_name='pub_date',
        ),
    ]
